namespace TasksCrud;

/// <summary>
/// Domain model — represents one task record in the application.
/// Maps to the Tasks table in SQLite.
/// </summary>
public class TaskItem
{
    public int Id { get; set; }                          // Primary key (auto-generated by DB)
    public string Title { get; set; } = string.Empty;  // Short name of the task
    public string Description { get; set; } = string.Empty;
    public bool IsCompleted { get; set; }               // false = Pending, true = Done
    public DateTime CreatedAt { get; set; }             // When the task was first saved
}
